version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: ./cat-sharing-test
    command: npm run start:dev
    ports:
    - "5000:5000"
    restart: on-failure
    volumes:
    - ./cat-sharing-test:/app
    depends_on:
      - db
    networks:
      default:
        aliases:
          - backend

  # frontend:
  #   build:
  #   command: npm run serve
  #   ports:
  #   - "8080:8080"
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #   networks:
  #     default:
  #       aliases:
  #         - frontend